package test

import (
	"testing"

	"github.com/ultipa/ultipa-go-driver/v5/sdk/configuration"
)

// TestSessionCreation tests basic session creation with auto-generated ID
func TestSessionCreation(t *testing.T) {
	session, err := client.Session(nil)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()

	// Verify session ID is generated
	if session.SessionID() == 0 {
		t.Error("Expected non-zero session ID")
	}

	t.Logf("Session created with ID: %d", session.SessionID())
}

// TestSessionWithConfig tests session creation with configuration
func TestSessionWithConfig(t *testing.T) {
	config := &configuration.SessionConfig{
		Graph:   "default",
		Timeout: 30,
	}

	session, err := client.Session(config)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()

	// Verify session ID is generated
	if session.SessionID() == 0 {
		t.Error("Expected non-zero session ID")
	}

	t.Logf("Session created with config, ID: %d", session.SessionID())
}

// TestSessionUql tests executing UQL within session
func TestSessionUql(t *testing.T) {
	session, err := client.Session(nil)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()

	// Execute UQL query
	resp, err := session.Uql("show().graph()", nil)
	if err != nil {
		t.Fatal(err)
	}

	if !resp.IsSuccess() {
		t.Fatalf("UQL query failed: %s", resp.Status.Message)
	}

	t.Logf("UQL executed successfully in session %d", session.SessionID())
}

// TestSessionGql tests executing GQL within session
func TestSessionGql(t *testing.T) {
	session, err := client.Session(nil)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()

	// Execute GQL query
	resp, err := session.Gql("MATCH (n) RETURN n LIMIT 5", nil)
	if err != nil {
		t.Fatal(err)
	}

	if !resp.IsSuccess() {
		t.Fatalf("GQL query failed: %s", resp.Status.Message)
	}

	t.Logf("GQL executed successfully in session %d", session.SessionID())
}

// TestSessionClose tests closing a session
func TestSessionClose(t *testing.T) {
	session, err := client.Session(nil)
	if err != nil {
		t.Fatal(err)
	}

	sessionID := session.SessionID()

	// Close the session
	err = session.Close()
	if err != nil {
		t.Fatalf("Failed to close session: %v", err)
	}

	t.Logf("Session %d closed successfully", sessionID)
}

// TestTransactionStartAndCommit tests starting a transaction and committing
func TestTransactionStartAndCommit(t *testing.T) {
	session, err := client.Session(nil)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()

	// Start transaction
	txn, err := session.StartTransaction(nil)
	if err != nil {
		t.Fatal(err)
	}

	// Verify transaction ID is generated by server
	if txn.TransactionID() == 0 {
		t.Error("Expected non-zero transaction ID from server")
	}

	t.Logf("Transaction started: %d", txn.TransactionID())

	// Verify session tracks the transaction
	if !session.HasTransaction() {
		t.Error("Session should have active transaction")
	}

	// Commit transaction
	err = txn.Commit()
	if err != nil {
		t.Fatalf("Failed to commit transaction: %v", err)
	}

	// Verify transaction is closed
	if !txn.IsClosed() {
		t.Error("Transaction should be closed after commit")
	}

	// Verify session no longer has transaction
	if session.HasTransaction() {
		t.Error("Session should not have active transaction after commit")
	}

	t.Log("Transaction committed successfully")
}

// TestTransactionStartAndRollback tests starting a transaction and rolling back
func TestTransactionStartAndRollback(t *testing.T) {
	session, err := client.Session(nil)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()

	// Start transaction
	txn, err := session.StartTransaction(nil)
	if err != nil {
		t.Fatal(err)
	}

	t.Logf("Transaction started: %d", txn.TransactionID())

	// Rollback transaction
	err = txn.Rollback()
	if err != nil {
		t.Fatalf("Failed to rollback transaction: %v", err)
	}

	// Verify transaction is closed
	if !txn.IsClosed() {
		t.Error("Transaction should be closed after rollback")
	}

	// Verify session no longer has transaction
	if session.HasTransaction() {
		t.Error("Session should not have active transaction after rollback")
	}

	t.Log("Transaction rolled back successfully")
}

// TestTransactionGql tests executing GQL within transaction
func TestTransactionGql(t *testing.T) {
	session, err := client.Session(nil)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()

	txn, err := session.StartTransaction(nil)
	if err != nil {
		t.Fatal(err)
	}
	defer txn.Close()

	// Execute GQL within transaction
	resp, err := txn.Gql("MATCH (n) RETURN n LIMIT 3", nil)
	if err != nil {
		t.Fatal(err)
	}

	if !resp.IsSuccess() {
		t.Fatalf("GQL query failed in transaction: %s", resp.Status.Message)
	}

	t.Logf("GQL executed successfully in transaction %d", txn.TransactionID())
}

// TestTransactionOnlyOnePerSession tests that only one transaction can be active per session
func TestTransactionOnlyOnePerSession(t *testing.T) {
	session, err := client.Session(nil)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()

	// Start first transaction
	txn1, err := session.StartTransaction(nil)
	if err != nil {
		t.Fatal(err)
	}

	t.Logf("First transaction started: %d", txn1.TransactionID())

	// Try to start second transaction - should fail
	_, err = session.StartTransaction(nil)
	if err == nil {
		t.Fatal("Expected error when starting second transaction, but got none")
	}

	t.Logf("Expected error received: %v", err)

	// Commit first transaction
	err = txn1.Commit()
	if err != nil {
		t.Fatal(err)
	}

	// Now we can start a new transaction
	txn2, err := session.StartTransaction(nil)
	if err != nil {
		t.Fatalf("Failed to start new transaction after committing first: %v", err)
	}
	defer txn2.Close()

	t.Logf("Second transaction started successfully: %d", txn2.TransactionID())
}

// TestTransactionAutoClose tests auto-rollback on Close()
func TestTransactionAutoClose(t *testing.T) {
	session, err := client.Session(nil)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()

	txn, err := session.StartTransaction(nil)
	if err != nil {
		t.Fatal(err)
	}

	txnID := txn.TransactionID()
	t.Logf("Transaction started: %d", txnID)

	// Close without commit or rollback - should auto-rollback
	err = txn.Close()
	if err != nil {
		t.Fatalf("Failed to close transaction: %v", err)
	}

	// Verify transaction is closed
	if !txn.IsClosed() {
		t.Error("Transaction should be closed after Close()")
	}

	// Verify session no longer has transaction
	if session.HasTransaction() {
		t.Error("Session should not have active transaction after auto-rollback")
	}

	t.Log("Transaction auto-rolled back on Close()")
}

// TestTransactionClosedOperations tests operations on closed transaction
func TestTransactionClosedOperations(t *testing.T) {
	session, err := client.Session(nil)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()

	txn, err := session.StartTransaction(nil)
	if err != nil {
		t.Fatal(err)
	}

	// Commit the transaction
	err = txn.Commit()
	if err != nil {
		t.Fatal(err)
	}

	// Try to execute query on closed transaction
	_, err = txn.Gql("MATCH (n) RETURN n LIMIT 1", nil)
	if err == nil {
		t.Fatal("Expected error when executing query on closed transaction")
	}

	t.Logf("Expected error received: %v", err)

	// Try to commit again
	err = txn.Commit()
	if err == nil {
		t.Fatal("Expected error when committing closed transaction")
	}

	t.Logf("Expected error on double commit: %v", err)

	// Try to rollback
	err = txn.Rollback()
	if err == nil {
		t.Fatal("Expected error when rolling back closed transaction")
	}

	t.Logf("Expected error on rollback after commit: %v", err)
}

// TestTransactionWithConfig tests transaction with configuration
func TestTransactionWithConfig(t *testing.T) {
	session, err := client.Session(nil)
	if err != nil {
		t.Fatal(err)
	}
	defer session.Close()

	txnConfig := &configuration.TransactionConfig{
		ReadOnly:           true,
		TransactionTimeout: 30,
	}

	txn, err := session.StartTransaction(txnConfig)
	if err != nil {
		t.Fatal(err)
	}
	defer txn.Close()

	t.Logf("Transaction with config started: %d", txn.TransactionID())

	// Execute read query
	resp, err := txn.Gql("MATCH (n) RETURN n LIMIT 1", nil)
	if err != nil {
		t.Fatal(err)
	}

	if !resp.IsSuccess() {
		t.Fatalf("Query failed: %s", resp.Status.Message)
	}

	t.Log("Read-only transaction executed successfully")
}

// TestSessionPlaceholder is a placeholder test
// Real tests require a database with s5.3 session/transaction support
func TestSessionPlaceholder(t *testing.T) {
	t.Log("✅ Proto files rebuilt successfully")
	t.Log("✅ SDK compiles without errors")
	t.Log("")
	t.Log("To test session and transaction features:")
	t.Log("1. Ensure Ultipa database has s5.3 support (session/transaction)")
	t.Log("2. Configure test/.env file with connection details")
	t.Log("3. Uncomment example tests in this file")
	t.Log("4. Run: go test -v ./test/session_example_test.go ./test/init_test.go")
}
