package session

import (
	"context"
	"fmt"

	"github.com/ultipa/ultipa-go-driver/v5/sdk/configuration"
	"github.com/ultipa/ultipa-go-driver/v5/sdk/http"
)

var (
	// ErrTransactionClosed indicates transaction has been closed
	ErrTransactionClosed = fmt.Errorf("transaction has been closed")
)

// Transaction represents a database transaction within a session
// Transaction ID is generated by the server when StartTransaction is called
// NOT thread-safe - caller must synchronize if used across goroutines
type Transaction struct {
	session       *Session
	transactionID uint64
	closed        bool
	config        *configuration.TransactionConfig
}

// newTransaction creates a new transaction (internal use only)
// Called by Session.StartTransaction after receiving transaction ID from server
func newTransaction(session *Session, transactionID uint64, config *configuration.TransactionConfig) *Transaction {
	return &Transaction{
		session:       session,
		transactionID: transactionID,
		closed:        false,
		config:        config,
	}
}

// TransactionID returns the transaction identifier (generated by server)
func (t *Transaction) TransactionID() uint64 {
	return t.transactionID
}

// IsClosed returns true if transaction has been closed
func (t *Transaction) IsClosed() bool {
	return t.closed
}

// Gql executes GQL within the transaction context
// Note: Transactions only support GQL, not UQL
func (t *Transaction) Gql(gql string, config *configuration.RequestConfig) (*http.Response, error) {
	if t.closed {
		return nil, ErrTransactionClosed
	}

	mergedConfig := t.mergeConfig(config)
	return t.session.conn.Gql(gql, mergedConfig)
}

// Commit commits the transaction
func (t *Transaction) Commit() error {
	return t.CommitWithContext(nil)
}

// CommitWithContext commits the transaction with context support
func (t *Transaction) CommitWithContext(ctx context.Context) error {
	if t.closed {
		return ErrTransactionClosed
	}

	// Check context cancellation
	if ctx != nil {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}
	}

	config := t.buildRequestConfig()
	resp, err := t.session.conn.Gql("COMMIT", config)

	if err != nil {
		return fmt.Errorf("failed to commit transaction: %w", err)
	}

	if !resp.IsSuccess() {
		return fmt.Errorf("commit failed: %s", resp.Status.Message)
	}

	// Mark transaction as closed and clear from session
	t.closed = true
	t.session.clearTransaction()

	return nil
}

// Rollback rolls back the transaction
func (t *Transaction) Rollback() error {
	return t.RollbackWithContext(nil)
}

// RollbackWithContext rolls back the transaction with context support
func (t *Transaction) RollbackWithContext(ctx context.Context) error {
	if t.closed {
		return ErrTransactionClosed
	}

	// Check context cancellation
	if ctx != nil {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}
	}

	config := t.buildRequestConfig()
	resp, err := t.session.conn.Gql("ROLLBACK", config)

	if err != nil {
		return fmt.Errorf("failed to rollback transaction: %w", err)
	}

	if !resp.IsSuccess() {
		return fmt.Errorf("rollback failed: %s", resp.Status.Message)
	}

	// Mark transaction as closed and clear from session
	t.closed = true
	t.session.clearTransaction()

	return nil
}

// Close closes the transaction
// If transaction is not committed or rolled back, it will be rolled back automatically
func (t *Transaction) Close() error {
	if t.closed {
		return nil
	}

	// Auto-rollback if not already committed/rolled back
	return t.Rollback()
}

// buildRequestConfig creates config with session/transaction context
func (t *Transaction) buildRequestConfig() *configuration.RequestConfig {
	config := configuration.MergeWithSessionDefaults(nil, t.session.config, t.session.sessionID, t.transactionID)

	// Apply transaction config if provided
	if t.config != nil {
		config.TransactionConfig = t.config
	}

	return config
}

// mergeConfig merges transaction config with provided config
// Similar to Session but always includes transaction ID
func (t *Transaction) mergeConfig(config *configuration.RequestConfig) *configuration.RequestConfig {
	merged := configuration.MergeWithSessionDefaults(config, t.session.config, t.session.sessionID, t.transactionID)

	// Override with transaction's config if provided
	if t.config != nil {
		merged.TransactionConfig = t.config
	}

	return merged
}
