// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: ha_status.proto

// HA status subset for driver-side follower-read routing. This is a deliberately MINIMAL,
// self-contained mirror of the HAService.GetStatus surface defined in the server's gqldb.proto
// (github.com/zhangjsff/gqldb-grpc/proto). Field numbers, message names, the proto package
// (gqldb) and the service/RPC names MUST match the server exactly — the gRPC method path is
// /gqldb.HAService/GetStatus, so a partial client stub (only GetStatus) interoperates with the
// full server service. Kept in its own file so a regen of the main gqldb.proto is untouched.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HAService_GetStatus_FullMethodName = "/gqldb.HAService/GetStatus"
)

// HAServiceClient is the client API for HAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HAService here declares ONLY GetStatus — the single RPC the driver needs for follower-read
// routing. The server implements the full HAService; method paths match, so this subset stub
// interoperates. (Add Join/RemoveNode/StepDown/etc. here only if the driver ever needs them.)
type HAServiceClient interface {
	// GetStatus returns the cluster status from the contacted node's perspective. Safe on any node,
	// including a single-node server (returns enabled=false).
	GetStatus(ctx context.Context, in *HAGetStatusRequest, opts ...grpc.CallOption) (*HAGetStatusResponse, error)
}

type hAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHAServiceClient(cc grpc.ClientConnInterface) HAServiceClient {
	return &hAServiceClient{cc}
}

func (c *hAServiceClient) GetStatus(ctx context.Context, in *HAGetStatusRequest, opts ...grpc.CallOption) (*HAGetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HAGetStatusResponse)
	err := c.cc.Invoke(ctx, HAService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HAServiceServer is the server API for HAService service.
// All implementations must embed UnimplementedHAServiceServer
// for forward compatibility.
//
// HAService here declares ONLY GetStatus — the single RPC the driver needs for follower-read
// routing. The server implements the full HAService; method paths match, so this subset stub
// interoperates. (Add Join/RemoveNode/StepDown/etc. here only if the driver ever needs them.)
type HAServiceServer interface {
	// GetStatus returns the cluster status from the contacted node's perspective. Safe on any node,
	// including a single-node server (returns enabled=false).
	GetStatus(context.Context, *HAGetStatusRequest) (*HAGetStatusResponse, error)
	mustEmbedUnimplementedHAServiceServer()
}

// UnimplementedHAServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHAServiceServer struct{}

func (UnimplementedHAServiceServer) GetStatus(context.Context, *HAGetStatusRequest) (*HAGetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedHAServiceServer) mustEmbedUnimplementedHAServiceServer() {}
func (UnimplementedHAServiceServer) testEmbeddedByValue()                   {}

// UnsafeHAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HAServiceServer will
// result in compilation errors.
type UnsafeHAServiceServer interface {
	mustEmbedUnimplementedHAServiceServer()
}

func RegisterHAServiceServer(s grpc.ServiceRegistrar, srv HAServiceServer) {
	// If the following call panics, it indicates UnimplementedHAServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HAService_ServiceDesc, srv)
}

func _HAService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HAGetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HAServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HAService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HAServiceServer).GetStatus(ctx, req.(*HAGetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HAService_ServiceDesc is the grpc.ServiceDesc for HAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gqldb.HAService",
	HandlerType: (*HAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _HAService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ha_status.proto",
}
