// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ha_status.proto

// HA status subset for driver-side follower-read routing. This is a deliberately MINIMAL,
// self-contained mirror of the HAService.GetStatus surface defined in the server's gqldb.proto
// (github.com/zhangjsff/gqldb-grpc/proto). Field numbers, message names, the proto package
// (gqldb) and the service/RPC names MUST match the server exactly — the gRPC method path is
// /gqldb.HAService/GetStatus, so a partial client stub (only GetStatus) interoperates with the
// full server service. Kept in its own file so a regen of the main gqldb.proto is untouched.

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeRole mirrors server gqldb.proto.
type NodeRole int32

const (
	NodeRole_NODE_ROLE_UNKNOWN  NodeRole = 0
	NodeRole_NODE_ROLE_LEADER   NodeRole = 1
	NodeRole_NODE_ROLE_FOLLOWER NodeRole = 2
	NodeRole_NODE_ROLE_LEARNER  NodeRole = 3 // non-voting member (joining / catching up)
)

// Enum value maps for NodeRole.
var (
	NodeRole_name = map[int32]string{
		0: "NODE_ROLE_UNKNOWN",
		1: "NODE_ROLE_LEADER",
		2: "NODE_ROLE_FOLLOWER",
		3: "NODE_ROLE_LEARNER",
	}
	NodeRole_value = map[string]int32{
		"NODE_ROLE_UNKNOWN":  0,
		"NODE_ROLE_LEADER":   1,
		"NODE_ROLE_FOLLOWER": 2,
		"NODE_ROLE_LEARNER":  3,
	}
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_ha_status_proto_enumTypes[0].Descriptor()
}

func (NodeRole) Type() protoreflect.EnumType {
	return &file_ha_status_proto_enumTypes[0]
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeRole.Descriptor instead.
func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return file_ha_status_proto_rawDescGZIP(), []int{0}
}

// NodeInfo mirrors server gqldb.proto.
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // raft advertise address
	Role          NodeRole               `protobuf:"varint,3,opt,name=role,proto3,enum=gqldb.NodeRole" json:"role,omitempty"`
	IsLeader      bool                   `protobuf:"varint,4,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	Voter         bool                   `protobuf:"varint,5,opt,name=voter,proto3" json:"voter,omitempty"` // true = voting member; false = learner / non-voter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_ha_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ha_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_ha_status_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_NODE_ROLE_UNKNOWN
}

func (x *NodeInfo) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *NodeInfo) GetVoter() bool {
	if x != nil {
		return x.Voter
	}
	return false
}

// HAStatus mirrors server gqldb.proto. applied_index/commit_index + members[] are what the driver
// reads to compute per-follower staleness: lag(follower) = leader.applied_index - follower.applied_index.
type HAStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"` // false when the server runs single-node (no coordinator)
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // raft state: Leader / Follower / Candidate / Shutdown
	IsLeader      bool                   `protobuf:"varint,4,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	LeaderId      string                 `protobuf:"bytes,5,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,6,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"` // host:port a driver can route writes to ("" if unknown)
	Term          uint64                 `protobuf:"varint,7,opt,name=term,proto3" json:"term,omitempty"`
	AppliedIndex  uint64                 `protobuf:"varint,8,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	CommitIndex   uint64                 `protobuf:"varint,9,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	Members       []*NodeInfo            `protobuf:"bytes,10,rep,name=members,proto3" json:"members,omitempty"`
	ComputeReady  bool                   `protobuf:"varint,11,opt,name=compute_ready,json=computeReady,proto3" json:"compute_ready,omitempty"` // this node's compute topology is ready to serve reads
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HAStatus) Reset() {
	*x = HAStatus{}
	mi := &file_ha_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HAStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HAStatus) ProtoMessage() {}

func (x *HAStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ha_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HAStatus.ProtoReflect.Descriptor instead.
func (*HAStatus) Descriptor() ([]byte, []int) {
	return file_ha_status_proto_rawDescGZIP(), []int{1}
}

func (x *HAStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *HAStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HAStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *HAStatus) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *HAStatus) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *HAStatus) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

func (x *HAStatus) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *HAStatus) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *HAStatus) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *HAStatus) GetMembers() []*NodeInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *HAStatus) GetComputeReady() bool {
	if x != nil {
		return x.ComputeReady
	}
	return false
}

type HAGetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HAGetStatusRequest) Reset() {
	*x = HAGetStatusRequest{}
	mi := &file_ha_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HAGetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HAGetStatusRequest) ProtoMessage() {}

func (x *HAGetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ha_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HAGetStatusRequest.ProtoReflect.Descriptor instead.
func (*HAGetStatusRequest) Descriptor() ([]byte, []int) {
	return file_ha_status_proto_rawDescGZIP(), []int{2}
}

type HAGetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *HAStatus              `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TimeCostNs    int64                  `protobuf:"varint,10,opt,name=time_cost_ns,json=timeCostNs,proto3" json:"time_cost_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HAGetStatusResponse) Reset() {
	*x = HAGetStatusResponse{}
	mi := &file_ha_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HAGetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HAGetStatusResponse) ProtoMessage() {}

func (x *HAGetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ha_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HAGetStatusResponse.ProtoReflect.Descriptor instead.
func (*HAGetStatusResponse) Descriptor() ([]byte, []int) {
	return file_ha_status_proto_rawDescGZIP(), []int{3}
}

func (x *HAGetStatusResponse) GetStatus() *HAStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HAGetStatusResponse) GetTimeCostNs() int64 {
	if x != nil {
		return x.TimeCostNs
	}
	return 0
}

var File_ha_status_proto protoreflect.FileDescriptor

const file_ha_status_proto_rawDesc = "" +
	"\n" +
	"\x0fha_status.proto\x12\x05gqldb\"\x95\x01\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12#\n" +
	"\x04role\x18\x03 \x01(\x0e2\x0f.gqldb.NodeRoleR\x04role\x12\x1b\n" +
	"\tis_leader\x18\x04 \x01(\bR\bisLeader\x12\x14\n" +
	"\x05voter\x18\x05 \x01(\bR\x05voter\"\xda\x02\n" +
	"\bHAStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1b\n" +
	"\tis_leader\x18\x04 \x01(\bR\bisLeader\x12\x1b\n" +
	"\tleader_id\x18\x05 \x01(\tR\bleaderId\x12\x1f\n" +
	"\vleader_addr\x18\x06 \x01(\tR\n" +
	"leaderAddr\x12\x12\n" +
	"\x04term\x18\a \x01(\x04R\x04term\x12#\n" +
	"\rapplied_index\x18\b \x01(\x04R\fappliedIndex\x12!\n" +
	"\fcommit_index\x18\t \x01(\x04R\vcommitIndex\x12)\n" +
	"\amembers\x18\n" +
	" \x03(\v2\x0f.gqldb.NodeInfoR\amembers\x12#\n" +
	"\rcompute_ready\x18\v \x01(\bR\fcomputeReady\"\x14\n" +
	"\x12HAGetStatusRequest\"`\n" +
	"\x13HAGetStatusResponse\x12'\n" +
	"\x06status\x18\x01 \x01(\v2\x0f.gqldb.HAStatusR\x06status\x12 \n" +
	"\ftime_cost_ns\x18\n" +
	" \x01(\x03R\n" +
	"timeCostNs*f\n" +
	"\bNodeRole\x12\x15\n" +
	"\x11NODE_ROLE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10NODE_ROLE_LEADER\x10\x01\x12\x16\n" +
	"\x12NODE_ROLE_FOLLOWER\x10\x02\x12\x15\n" +
	"\x11NODE_ROLE_LEARNER\x10\x032O\n" +
	"\tHAService\x12B\n" +
	"\tGetStatus\x12\x19.gqldb.HAGetStatusRequest\x1a\x1a.gqldb.HAGetStatusResponseB'Z%github.com/zhangjsff/gqldb-grpc/protob\x06proto3"

var (
	file_ha_status_proto_rawDescOnce sync.Once
	file_ha_status_proto_rawDescData []byte
)

func file_ha_status_proto_rawDescGZIP() []byte {
	file_ha_status_proto_rawDescOnce.Do(func() {
		file_ha_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ha_status_proto_rawDesc), len(file_ha_status_proto_rawDesc)))
	})
	return file_ha_status_proto_rawDescData
}

var file_ha_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ha_status_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ha_status_proto_goTypes = []any{
	(NodeRole)(0),               // 0: gqldb.NodeRole
	(*NodeInfo)(nil),            // 1: gqldb.NodeInfo
	(*HAStatus)(nil),            // 2: gqldb.HAStatus
	(*HAGetStatusRequest)(nil),  // 3: gqldb.HAGetStatusRequest
	(*HAGetStatusResponse)(nil), // 4: gqldb.HAGetStatusResponse
}
var file_ha_status_proto_depIdxs = []int32{
	0, // 0: gqldb.NodeInfo.role:type_name -> gqldb.NodeRole
	1, // 1: gqldb.HAStatus.members:type_name -> gqldb.NodeInfo
	2, // 2: gqldb.HAGetStatusResponse.status:type_name -> gqldb.HAStatus
	3, // 3: gqldb.HAService.GetStatus:input_type -> gqldb.HAGetStatusRequest
	4, // 4: gqldb.HAService.GetStatus:output_type -> gqldb.HAGetStatusResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ha_status_proto_init() }
func file_ha_status_proto_init() {
	if File_ha_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ha_status_proto_rawDesc), len(file_ha_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ha_status_proto_goTypes,
		DependencyIndexes: file_ha_status_proto_depIdxs,
		EnumInfos:         file_ha_status_proto_enumTypes,
		MessageInfos:      file_ha_status_proto_msgTypes,
	}.Build()
	File_ha_status_proto = out.File
	file_ha_status_proto_goTypes = nil
	file_ha_status_proto_depIdxs = nil
}
